import { readFileSync, writeFileSync } from 'node:fs';
const target = new URL('../src/generated/api.ts', import.meta.url);
const content = `// Generated by scripts/generate-api.mjs
export type HealthResponse = { status: 'ok'; service: 'api' };
export type ReadyResponse = { status: 'ready' | 'not_ready'; checks: Record<'database' | 'redis', 'ok' | 'unavailable'> };
`;
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== content) { console.error('Generated API contract is out of date'); process.exit(1); }
} else writeFileSync(target, content);
